/*   $Source: /Users/kamil/work/gasnet-cvs2/gasnet/Attic/gasnet_sysv.c,v $
 *     $Date: 2009/08/26 08:33:55 $
 * $Revision: 1.1.4.34 $
 * Description: GASNet infrastructure for shared memory communications
 * Copyright 2007, Dan Bonachea <bonachea@cs.berkeley.edu>
 * Terms of use are as specified in license.txt
 */

#if GASNET_SYSV

#include <gasnet_internal.h>
#include <gasnet_core_internal.h> /* for gasnetc_{Short,Medium,Long} */

/* Do this here to avoid pulling gasnet_handler.h into gasnet_sysv.h */
#include <gasnet_handler.h> /* Need gasneti_handler_fn_t */
extern gasneti_handler_fn_t gasnetc_get_handler(int handler_id);

uintptr_t *gasneti_seginfo_correction;
int gasnetc_sysv_init = 0;

static void *gasnetc_sysvnet_region;
static gasneti_atomic_t *gasneti_barrier_counter = NULL;

void gasnetc_init_sysv(gasneti_bootstrapExchangefn_t exchangefn) {
  size_t vnetsz, mmapsz;

  gasneti_sysvnodes = gasneti_nodemap_local_count;
  gasneti_firstsysvnode = gasneti_nodemap[gasneti_mynode];
  gasneti_mysysvnode = gasneti_nodemap_local_rank;

#if GASNET_CONDUIT_SMP_SYSV || GASNET_CONDUIT_SMP
  gasneti_assert(gasneti_sysvnodes == gasneti_nodes);
  gasneti_assert(gasneti_firstsysvnode == 0);
  gasneti_assert(gasneti_mysysvnode == gasneti_mynode);
#endif

  /* setup filenames, unless exchangefn is NULL (indicating caller took care of it) */
  if (exchangefn != NULL) {
    char (*exchg)[GASNETI_SYSV_UNIQUE_LEN];
    char unique[GASNETI_SYSV_UNIQUE_LEN];

    /* First in each supernode generates the names and returns the unique identifier */
    if (gasneti_mysysvnode == 0) {
      const char *tmp = gasneti_sysv_makenames(NULL);
      memcpy(unique, tmp, GASNETI_SYSV_UNIQUE_LEN);
    }

    /* Conduit's exchangefn is used as a supernode-scoped bcast to
     * communicate the unique identifier generated by the firsts */
    exchg = gasneti_malloc(gasneti_nodes * GASNETI_SYSV_UNIQUE_LEN);
    (*exchangefn)(unique, GASNETI_SYSV_UNIQUE_LEN, exchg);

    /* Non-first nodes now generate the same names from the unique identifier */
    if (gasneti_mysysvnode != 0) {
      (void)gasneti_sysv_makenames((const char *)(exchg + gasneti_firstsysvnode));
    }
    gasneti_free(exchg);
  }
    
  /* setup vnet shared memory region for AM infrastructure and supernode barrier.
   */
  vnetsz = gasneti_sysvnet_memory_needed(gasneti_sysvnodes); 
  mmapsz = (2*vnetsz) + GASNETI_SYSVNET_PAGESIZE; /* Extra page is for the bootstrapBarrier */
  gasnetc_sysvnet_region = gasneti_mmap_vnet(mmapsz);
  if (gasnetc_sysvnet_region == NULL) {
    gasneti_unlink_vnet();
    gasneti_fatalerror("Failed to mmap %lu bytes for shared memory Active Messages region.",
                       (unsigned long)mmapsz);
  }
  
  /* Prepare the barrier */
  gasneti_barrier_counter = (gasneti_atomic_t *)((uintptr_t)gasnetc_sysvnet_region + 2*vnetsz);

  /* Unlink the shared memory file to prevent leaks */
  gasneti_sysvnet_bootstrapBarrier();
  gasneti_unlink_vnet();

  /* Collective call to initialize Shared AM "networks" */
  gasneti_sysvnet_init(&gasneti_request_sysvnet, gasnetc_sysvnet_region,
                       vnetsz, gasneti_firstsysvnode, gasneti_sysvnodes);
  gasneti_sysvnet_init(&gasneti_reply_sysvnet, (void*)((uintptr_t)gasnetc_sysvnet_region + vnetsz),
                       vnetsz, gasneti_firstsysvnode, gasneti_sysvnodes);

  /* Ensure all peers are initialized before return */
  gasneti_sysvnet_bootstrapBarrier();
}

/*******************************************************************************
 * "SysV Net":  virtual network between peers in a shared memory supernode 
 ******************************************************************************/
/* # of nodes in my supernode, lowest of contiguous gasnet node #s in
 * supernode, and my 0-based rank within it */
gasnet_node_t gasneti_sysvnodes = 0;
gasnet_node_t gasneti_firstsysvnode = (gasnet_node_t)(-1);
gasnet_node_t gasneti_mysysvnode = (gasnet_node_t)(-1);

size_t gasneti_sysvnet_max_payload() {
  return GASNETI_SYSVNET_MAX_PAYLOAD;
}

/******************************************************************************
 * Payload memory allocator interface.
 *
 * Keep the payload allocator interface clean, so we can replace the current
 * algorithm (circular queue of fixed-length buffers) with something else
 * (like a full-blown memory allocator) if needed.
 * - It should be mainly a matter of autotools goopery to replace this
 *   implementation with umalloc, should that prove to be a good idea.
 * - Naming note: 'allocator' = "payload allocator", just like a "J. Lo"
 *   allocator would would be called "jallocator".  Isn't that obvious?
 ******************************************************************************/

/* Memory layout of allocator.
 *
 * Logically, we have this layout:
 *  
 *    1) Atomic used by allocator as 'in use' bit
 *    2) A gasnet_sysvnet_payload_t struct, used by sysvnet
 *    3) The rest of the page-sized, for payload.
 *
 * Suboptimal hack: I don't know my alignment niceties well enough, so I'm
 * having the allocator treat the space as
 *  
 *    1) A gasnet_sysvnet_payload_t sized-space, which I cast to a (definitely
 *       smaller) atomic_t for use as the 'in_use' bit.
 *    2) A second gasnet_sysvnet_payload_t, used by sysvnet.  This is the
 *       'start' of the memory returned by the allocator, as sysvent sees it.
 *    3) A third gasnet_sysvnet_payload_t, which is cast to 'void *', and is
 *       the start of the payload.
 */ 

/* sizeof(gasneti_sysvnet_allocator_block) == GASNETI_SYSVNET_PAGESIZE 
 * - if not, adjust definition of GASNETI_SYSVNET_MAX_PAYLOAD */
typedef struct gasneti_sysvnet_allocator_block {
  union {
    gasneti_atomic_t in_use;
    gasneti_sysvnet_payload_info_t padding;
  } alignmentFun; 
  gasneti_sysvnet_payload_t payload_t;
} gasneti_sysvnet_allocator_block_t;

/* This implementation uses a circular queue of fixed-size payloads */
typedef struct gasneti_sysvnet_allocator {
  gasneti_sysvnet_allocator_block_t *queue;
  gasneti_mutex_t next_lock;    /* only locked by owning process */
  gasneti_sysvnet_allocator_block_t *next;
  gasneti_sysvnet_allocator_block_t *justpastlast;
  char _pad[GASNETI_CACHE_LINE_BYTES];
} gasneti_sysvnet_allocator_t;

/* WARNING: the amount requested from this allocator must be less than 
 * sizeof(gasneti_sysvnet_payload_t)
 * - returns NULL if no memory available
 */
static gasneti_sysvnet_allocator_t *gasneti_sysvnet_init_allocator(void *region, size_t len);
static void * gasneti_sysvnet_alloc(gasneti_sysvnet_allocator_t *a, size_t nbytes);
/* Frees memory.  Note that this must be callable by a different node */
static void gasneti_sysvnet_free(gasneti_sysvnet_allocator_t *a, void *p);

/******************************************************************************
 * </Payload memory allocator interface>
 ******************************************************************************/

/* Per node view of 'network' of queues in supernode 
 * - Note that this struct itself is not stored in shared memory. 
 */
struct gasneti_sysvnet {
  gasnet_node_t firstnode;          /* first gasnet node in this supernode */
  gasnet_node_t nodecount;          /* nodes in supernode */ 
  gasnet_node_t nextindex;          /* index of next node to check for msgs */
  gasneti_mutex_t index_lock;       /* protects updates to nextindex */
  /* my 'in' queues are other nodes' 'out' queues */
  gasneti_sysvnet_queue_t **in_queues;
  gasneti_sysvnet_queue_t **out_queues;
  /* only need to see one's own allocator */
  gasneti_sysvnet_allocator_t *my_allocator;
};

#define sysvnode(vnet, gasnet_node) \
        (gasnet_node - vnet->firstnode)

#define gasneti_assert_align(p, align) \
        gasneti_assert((((uintptr_t)p) % align) == 0)

/* Macros for determining the offset and the real address, used for
 * the addresses inside the sysnet region */
#define gasneti_sysv_offset(addr) \
                (void *)((uintptr_t)(addr) - (uintptr_t)gasnetc_sysvnet_region)

#define gasneti_sysv_addr(addr) \
                (void *)((uintptr_t)(addr) + (uintptr_t)gasnetc_sysvnet_region)


static int get_queue_depth(gasnet_node_t nodes) 
{
  int val = gasneti_getenv_int_withdefault("GASNET_SYSVNET_QUEUE_DEPTH", GASNETI_SYSVNET_DEFAULT_QUEUE_DEPTH, 0);
  if (val > GASNETI_SYSVNET_MAX_QUEUE_DEPTH) {
    fprintf(stderr, "GASNET_SYSVNET_QUEUE_DEPTH (%d) larger than max: using max (%d)\n",
            val, GASNETI_SYSVNET_MAX_QUEUE_DEPTH);
    val = GASNETI_SYSVNET_MAX_QUEUE_DEPTH;
  } else if (val < GASNETI_SYSVNET_MIN_QUEUE_DEPTH) {
    fprintf(stderr, "GASNET_SYSVNET_QUEUE_DEPTH (%d) < than SysV nodes (%d): using %d\n",
            val, GASNETI_SYSVNET_MIN_QUEUE_DEPTH, GASNETI_SYSVNET_MIN_QUEUE_DEPTH);
    val = GASNETI_SYSVNET_MIN_QUEUE_DEPTH;
  }
  return val;
}

static uintptr_t get_queue_mem(int nodes) 
{
  /* theoretical limit = 1 send buffer per peer? 
   * - future implementations may also need some space for allocator's metadata */
  size_t minsize = GASNETI_SYSVNET_PAGESIZE*nodes*2;
  uintptr_t pernode = gasneti_getenv_int_withdefault("GASNET_SYSVNET_QUEUE_MEMORY", 
                    GASNETI_SYSVNET_DEFAULT_QUEUE_MEMORY, 1<<20);
  if (pernode > GASNETI_SYSVNET_MAX_QUEUE_MEMORY) {
    fprintf(stderr, "GASNET_SYSVNET_QUEUE_MEMORY (%ld) larger than max: using max (%ld)\n",
            (long)pernode, (long)GASNETI_SYSVNET_MAX_QUEUE_MEMORY);
    pernode = GASNETI_SYSVNET_MAX_QUEUE_MEMORY;
  } else if (pernode < minsize) {
    fprintf(stderr, "GASNET_SYSVNET_QUEUE_MEMORY (%ld) smaller than min: using min (%ld)\n",
            (long)pernode, (long)minsize);
    pernode = minsize;
  }
  gasneti_assert(pernode > 0);

  /* round up to multiple of payload size */
  if ( (pernode % sizeof(gasneti_sysvnet_payload_t)) != 0)
    pernode = ((pernode / sizeof(gasneti_sysvnet_payload_t)) + 1) 
                * sizeof(gasneti_sysvnet_payload_t);
  return pernode;
}

static size_t gasneti_sysvnet_memory_needed_pernode(gasnet_node_t nodes)
{
  size_t size = 0;

  gasneti_sysvnet_queue_depth = get_queue_depth(nodes);
  gasneti_sysvnet_queue_mem = get_queue_mem(nodes);

  /* Message infos and queue */
  size = sizeof(gasneti_sysvnet_queue_t)*(nodes);
  size += sizeof(gasneti_sysvnet_msg_t)*gasneti_sysvnet_queue_depth*(nodes-1);
  size = round_up_to_sysvpage(size);
  size += sizeof(gasneti_sysvnet_allocator_t);
  size = round_up_to_sysvpage(size);
  size += gasneti_sysvnet_queue_mem;  
  size = round_up_to_sysvpage(size);

  return size;
}

size_t gasneti_sysvnet_memory_needed(gasnet_node_t nodes)
{
  return gasneti_sysvnet_memory_needed_pernode(nodes) * nodes;
}

#define SYSV_OFFSET
#ifdef SYSV_OFFSET

static void init_queue(gasneti_sysvnet_queue_t *q, gasneti_sysvnet_msg_t *msgs,
                       int depth)
{
  int i;

  /* Instead of using the "real" msgs address, we use only the offset with respect to the beginning of
   * the mapping */
  q->queue = q->recv_next = q->send_next = (gasneti_sysvnet_msg_t *)gasneti_sysv_offset(msgs);
  q->justpastlast = (gasneti_sysvnet_msg_t *)gasneti_sysv_offset(msgs) + depth;
  gasneti_mutex_init(&q->recv_lock);
  gasneti_mutex_init(&q->send_lock);

  for (i = 0; i < depth; i++) {
    gasneti_atomic_set(&msgs->state, GASNETI_SYSVNET_EMPTY, 0);
    msgs++;
  }

}
#else

static void init_queue(gasneti_sysvnet_queue_t *q, gasneti_sysvnet_msg_t *msgs,
                       int depth)
{
  int i;

  q->queue = q->recv_next = q->send_next = msgs;
  q->justpastlast = msgs + depth;
  gasneti_mutex_init(&q->recv_lock);
  gasneti_mutex_init(&q->send_lock);

  //printf("%d> init_queue address q->send_next %u, q->send_next->state %u q->send_next->state.ctr %u\n",gasneti_mysysvnode,&q->send_next, &q->send_next->state, &q->send_next->state.ctr);
  for (i = 0; i < depth; i++) {
    gasneti_atomic_set(&msgs->state, GASNETI_SYSVNET_EMPTY, 0);
    msgs++;
  }
}

#endif

static void gasneti_sysvnet_init_my_sysv(gasneti_sysvnet_t *pvnet, char * myregion, 
                                  gasnet_node_t firstnode, gasnet_node_t nodes)
{
  int i;
  gasneti_sysvnet_queue_t *myqueues;
  gasneti_sysvnet_msg_t   *mymsgs, *remote_mymsgs;
  void *alloc_region;
  gasneti_assert_align(myregion, GASNETI_SYSVNET_PAGESIZE);

  /* NOTE: other init code relies on queues being at start of region */
  myqueues = (gasneti_sysvnet_queue_t *)myregion;
  mymsgs = (gasneti_sysvnet_msg_t *)(((char*)myqueues) 
                                      + sizeof(gasneti_sysvnet_queue_t)*nodes);  
  gasneti_assert_align(mymsgs, GASNETI_CACHE_LINE_BYTES);
  alloc_region = ((char*)mymsgs) + 
        sizeof(gasneti_sysvnet_msg_t)*gasneti_sysvnet_queue_depth*(nodes-1);
  alloc_region = (void *)round_up_to_sysvpage(alloc_region);

  for (i = 0; i < nodes; i++) {
    if (i == gasneti_mysysvnode) {
      memset(&myqueues[i], 0, sizeof(gasneti_sysvnet_queue_t));
    } else {
      init_queue(&myqueues[i], mymsgs, gasneti_sysvnet_queue_depth);
      mymsgs += gasneti_sysvnet_queue_depth;
    }
  }
  pvnet->my_allocator = 
    gasneti_sysvnet_init_allocator(alloc_region, gasneti_sysvnet_queue_mem);

  pvnet->nextindex = 0;
  gasneti_mutex_init(&pvnet->index_lock);
}

/* Initializes the sysvnet region. Called from each node twice: 
 * to initialize sysvnet_request and sysvnet_reply */
void gasneti_sysvnet_init(gasneti_sysvnet_t **pvnet, void *start, size_t nbytes, 
                          gasnet_node_t firstnode, gasnet_node_t sysvnodes)
{
  gasneti_sysvnet_t *vnet;
  gasnet_node_t i, othernode;
  size_t szpernode, regionlen;
  void *region, *myregion;

  /* make sure that our max buffer size isn't smaller than whatever network
   * is being used */
  gasneti_assert(GASNETC_MAX_MEDIUM_SYSV < GASNETI_SYSVNET_MAX_PAYLOAD);

  region = start;
  region = (void *)round_up_to_sysvpage(region);

  regionlen = nbytes - ( ((uintptr_t)region)-((uintptr_t)start));
  szpernode = gasneti_sysvnet_memory_needed_pernode(sysvnodes);
  if (regionlen < szpernode * sysvnodes) 
    gasneti_fatalerror("Internal error: not enough memory for sysvnet: \n"
                       " given %lu effective bytes, but need %lu", 
                       (unsigned long)regionlen, (unsigned long)(szpernode * sysvnodes));
  vnet = gasneti_malloc(sizeof(gasneti_sysvnet_t));
  vnet->firstnode = firstnode;
  vnet->nodecount = sysvnodes;
  myregion = (void *)( ((uintptr_t)region) + (szpernode*gasneti_mysysvnode));
  /* collective call, so each process inits its own region.
   * To allow non-fixed mapping of the sysvnet memory, we initialize
   * each reqion using the offset-addresses */
  gasneti_sysvnet_init_my_sysv(vnet, myregion, firstnode, sysvnodes);

  /* initialize queue pointers */
  vnet->in_queues = gasneti_malloc(sizeof(gasneti_sysvnet_queue_t*)*sysvnodes);
  vnet->out_queues = gasneti_malloc(sizeof(gasneti_sysvnet_queue_t*)*sysvnodes);
  for (i = 0; i < sysvnodes; i++) {
    vnet->in_queues[i] = ((gasneti_sysvnet_queue_t *)myregion) + i;
    vnet->out_queues[i] = ((gasneti_sysvnet_queue_t *) (((uintptr_t)region)+(szpernode*i))) 
                          + gasneti_mysysvnode;
  }

  *pvnet = vnet;
}

void * gasneti_sysvnet_get_send_buffer(gasneti_sysvnet_t *vnet, size_t nbytes, 
                                       gasnet_node_t target)
{
  gasneti_sysvnet_payload_t *p;
  void *retval = NULL;
  
  gasneti_assert(nbytes <= GASNETI_SYSVNET_MAX_PAYLOAD);

  p = gasneti_sysvnet_alloc(vnet->my_allocator, sizeof(gasneti_sysvnet_payload_t));
  if (p != NULL) {
    p->info.msg = NULL;
    p->info.allocator = vnet->my_allocator;
    retval = p->payload;
  }
  
  return retval;
}


#ifdef SYSV_OFFSET

int gasneti_sysvnet_deliver_send_buffer(gasneti_sysvnet_t *vnet, void *buf, 
                                        size_t nbytes, gasnet_node_t target)
{
  int retval = -1;
  gasneti_sysvnet_msg_t *q_send_next;
  gasneti_sysvnet_payload_t *p;
  gasneti_sysvnet_queue_t *q = vnet->out_queues[sysvnode(vnet, target)];
  gasneti_assert(q != NULL);

  gasneti_mutex_lock(&q->send_lock);
  
  /* Get the actual address of q->send_next (q-> contains only offsets) */
  q_send_next = (gasneti_sysvnet_msg_t *)gasneti_sysv_addr(q->send_next);

   /* This code assumes that if the current 'send_node' isn't free yet, there
   * are no free slots in the recipient's queue.  Since there is only one
   * sender, one receiver, and the receiver consumes messages in order, this
   * should be true, so no scan over the list is needed. */
  if (gasneti_atomic_read(&q_send_next->state, 0) == GASNETI_SYSVNET_EMPTY) {
    retval = 0;
    /* fill in message info. Instead of buf we use offset since it
     * will be read by another node wich does not have identical sysvnet
     * memory mapping */
    q_send_next->addr = gasneti_sysv_offset(buf);
    q_send_next->len = nbytes;
    /* set pointer to msg in buffer */
    p = sysvnet_get_struct_addr_from_field_addr(gasneti_sysvnet_payload_t, payload, buf);
    gasneti_assert(buf == &p->payload);
    p->info.msg = gasneti_sysv_offset(q_send_next);
    /* Perform write flush before writing ready bit */
    gasneti_atomic_set(&q_send_next->state, GASNETI_SYSVNET_FULL, GASNETI_ATOMIC_REL);
    /* Advance q->send_next (logic is the same regardless of addr vs. offset) */
    if (++q->send_next == q->justpastlast)
      q->send_next = q->queue;
  }
 
  gasneti_mutex_unlock(&q->send_lock);

  return retval;
}


int gasneti_sysvnet_recv(gasneti_sysvnet_t *vnet, void **pbuf, size_t *psize, 
                         gasnet_node_t *from)
{
  const int nodecount = vnet->nodecount;
  int i;
   
  for (i = 0; i < nodecount; i++) {
    int tmp, nextindex;

    /* Ensure fairness: next check starts with next node. */
    gasneti_mutex_lock(&vnet->index_lock);
      nextindex = vnet->nextindex;
      tmp = nextindex + 1;
      if (tmp == nodecount) tmp = 0;
      vnet->nextindex = tmp;
    gasneti_mutex_unlock(&vnet->index_lock);
 
    if (nextindex != gasneti_mysysvnode) {
      gasneti_sysvnet_queue_t *q = vnet->in_queues[nextindex];
      gasneti_sysvnet_msg_t *q_recv_next;
      
      gasneti_assert(q != NULL);
      gasneti_mutex_lock(&q->recv_lock);

      /* Get the actual address of q->recv_next (q-> contains only offsets) */
      q_recv_next = (gasneti_sysvnet_msg_t *)gasneti_sysv_addr(q->recv_next);
      
      if (gasneti_atomic_compare_and_swap(&q_recv_next->state, GASNETI_SYSVNET_FULL,
                                          GASNETI_SYSVNET_BUSY, GASNETI_ATOMIC_ACQ_IF_TRUE)) {
        /* Transform the offset in q_recv_next->addr into a real address */
        *pbuf = gasneti_sysv_addr(q_recv_next->addr);
        *psize = q_recv_next->len;

	/* Advance q->recv_next (logic is the same regardless of addr vs. offset) */
        if (++q->recv_next == q->justpastlast)
           q->recv_next = q->queue;

        gasneti_mutex_unlock(&q->recv_lock);
        *from = nextindex + vnet->firstnode;
        return 0;
      }
        
      gasneti_mutex_unlock(&q->recv_lock);
    }
  }
  
  return -1;
}
#else

int gasneti_sysvnet_deliver_send_buffer(gasneti_sysvnet_t *vnet, void *buf, 
                                        size_t nbytes, gasnet_node_t target)
{
  int retval = -1;
  gasneti_sysvnet_payload_t *p;
  gasneti_sysvnet_queue_t *q = vnet->out_queues[sysvnode(vnet, target)];
  gasneti_assert(q != NULL);
  gasneti_mutex_lock(&q->send_lock);

  /* This code assumes that if the current 'send_node' isn't free yet, there
   * are no free slots in the recipient's queue.  Since there is only one
   * sender, one receiver, and the receiver consumes messages in order, this
   * should be true, so no scan over the list is needed. */
  if (gasneti_atomic_read(&q->send_next->state, 0) == GASNETI_SYSVNET_EMPTY) {
    retval = 0;
    /* fill in message info */
    q->send_next->addr = buf;
    q->send_next->len = nbytes;
    /* set pointer to msg in buffer */
    p = sysvnet_get_struct_addr_from_field_addr(gasneti_sysvnet_payload_t, payload, buf);
    gasneti_assert(buf == &p->payload);
    p->info.msg = q->send_next;
    /* Perform write flush before writing ready bit */
    gasneti_atomic_set(&q->send_next->state, GASNETI_SYSVNET_FULL, GASNETI_ATOMIC_REL);
    if (++q->send_next == q->justpastlast)
      q->send_next = q->queue;
  }
  gasneti_mutex_unlock(&q->send_lock);
  return retval;
}

int gasneti_sysvnet_recv(gasneti_sysvnet_t *vnet, void **pbuf, size_t *psize, 
                         gasnet_node_t *from)
{
  int i;
  for (i = 0; i < vnet->nodecount; i++) {
    if (vnet->nextindex != gasneti_mysysvnode) {
      gasneti_sysvnet_queue_t *q = vnet->in_queues[vnet->nextindex];
      gasneti_assert(q != NULL);
      gasneti_mutex_lock(&q->recv_lock);
      if (gasneti_atomic_compare_and_swap(&q->recv_next->state, GASNETI_SYSVNET_FULL,
                                          GASNETI_SYSVNET_BUSY, GASNETI_ATOMIC_ACQ_IF_TRUE)) {
        *pbuf = q->recv_next->addr;
        *psize = q->recv_next->len;
        if (++q->recv_next == q->justpastlast)
          q->recv_next = q->queue;
        gasneti_mutex_unlock(&q->recv_lock);
        *from = vnet->nextindex + vnet->firstnode;
        /* Ensure fairness: next check starts with next node */
        if (++vnet->nextindex == vnet->nodecount) 
          vnet->nextindex = 0;
        return 0;
      }
      gasneti_mutex_unlock(&q->recv_lock);
    }
    if (++vnet->nextindex == vnet->nodecount) 
      vnet->nextindex = 0;
  }
  return -1;
}

#endif

/* TODO: the current behavior if a user forgets to call this function is
 * NASTY--the message stays marked as state==FULL, which will cause
 * senders to think the queue is full.  This could cause
 * deadlock and/or lots of confusion (for me it was the latter).
 */
void gasneti_sysvnet_recv_release(gasneti_sysvnet_t *vnet, void *buf)
{
  /* Address we handed out was the addr of the 'payload' field */
  gasneti_sysvnet_payload_t *p = 
    sysvnet_get_struct_addr_from_field_addr(gasneti_sysvnet_payload_t,
                                            payload, buf);
  gasneti_assert(buf == &p->payload);
  gasneti_assert(p && p->info.msg && p->info.allocator);
  /* mark msg as free */
  p->info.msg = gasneti_sysv_addr(p->info.msg);
  gasneti_assert(gasneti_atomic_read(&p->info.msg->state,0) == GASNETI_SYSVNET_BUSY);
  gasneti_atomic_set(&p->info.msg->state, GASNETI_SYSVNET_EMPTY, 0);
  gasneti_sysvnet_free(p->info.allocator, p);
}


/******************************************************************************
 * Sysvnet bootstrap barrier
 * - TODO: only good a finite number of times before it wraps!
 ******************************************************************************/
void gasneti_sysvnet_bootstrapBarrier(void)
{
  gasneti_atomic_val_t curr, target;

  gasneti_assert(gasneti_barrier_counter != NULL);
  gasneti_assert(gasneti_sysvnodes > 0);

  curr = gasneti_atomic_read(gasneti_barrier_counter, 0);
  target = gasneti_sysvnodes + curr - (curr % gasneti_sysvnodes);
  gasneti_assert_always(target > curr); /* Die if we were ever to wrap */

  gasneti_atomic_increment(gasneti_barrier_counter, GASNETI_ATOMIC_REL);
  gasneti_waitwhile(gasneti_atomic_read(gasneti_barrier_counter, 0) < target);
}

/******************************************************************************
 * Helper for Sysvnet bootstrap broadcast and exchange
 ******************************************************************************/
static void gasneti_sysvnet_bcast_inner(gasneti_sysvnet_t *vnet, void *src, 
                                        size_t len, void *dest, int rootsysvnode)
{
  if (gasneti_mysysvnode == rootsysvnode) {
    gasnet_node_t i, to;
    void *msg;

    for (i = 0, to = vnet->firstnode; i < vnet->nodecount; i++, to++) {
      if (i == gasneti_mysysvnode) continue;
      msg = gasneti_sysvnet_get_send_buffer(vnet, len, to);
      if (msg) {
        memcpy(msg, src, len);
        if (gasneti_sysvnet_deliver_send_buffer(vnet, msg, len, to)) {
          gasneti_fatalerror("T%d: Can't deliver msg to node %d during bootstrap collective", 
                             gasneti_mynode, to);
        }
      } else {
        gasneti_fatalerror("T%d: Couldn't get send buffer during bootstrap collective", 
                           gasneti_mynode);
      }
    }
    memmove(dest, src, len);
  } else {
    gasnet_node_t i, from;
    void *msg;
    size_t inlen;

    gasneti_waitwhile (gasneti_sysvnet_recv(vnet, &msg, &inlen, &from));
    if (len != inlen) {
      gasneti_fatalerror("T%d: got unexpected msg length (%ld) during bootstrap collective", 
                         gasneti_mynode, (long int)inlen);
    }
    if (sysvnode(vnet, from) != rootsysvnode) {
      gasneti_fatalerror("T%d: got unexpected source node (%d) during bootstrap collective", 
                         gasneti_mynode, (int)from);
    }
    memcpy(dest, msg, len);
    gasneti_sysvnet_recv_release(vnet, msg);
  }
}

/******************************************************************************
 * Sysvnet bootstrap broadcast
 * - Rootsysvnode is supernode-local rank
 * - Barriers ensure ordering w.r.t sends that precede or follow
 ******************************************************************************/
void gasneti_sysvnet_bootstrapBroadcast(gasneti_sysvnet_t *vnet, void *src, 
                                        size_t len, void *dest, int rootsysvnode)
{
  gasneti_assert(vnet != NULL);
  gasneti_sysvnet_bootstrapBarrier();
  gasneti_sysvnet_bcast_inner(vnet, src, len, dest, rootsysvnode);
}

/******************************************************************************
 * Sysvnet bootstrap exchange
 * - Barriers ensure ordering w.r.t sends that precede or follow
 ******************************************************************************/
void gasneti_sysvnet_bootstrapExchange(gasneti_sysvnet_t *vnet, void *src, 
                                       size_t len, void *dest)
{
  gasnet_node_t i;

  gasneti_assert(vnet != NULL);

  /* All nodes broadcast their contribution in turn */
  for (i = 0; i < vnet->nodecount; i++) {
    void *dest_elem = (void*)((uintptr_t)dest + (i*len));
    gasneti_sysvnet_bootstrapBarrier(); 
    gasneti_sysvnet_bcast_inner(vnet, src, len, dest_elem, i);
  }
}


/******************************************************************************
 * Allocator implementation
 ******************************************************************************/

static gasneti_sysvnet_allocator_t *gasneti_sysvnet_init_allocator(void *region, size_t len)
{
  int i;
  int count = len / sizeof(gasneti_sysvnet_allocator_block_t);
  gasneti_sysvnet_allocator_block_t *tmp;

  /* This implementation doesn't need to put allocator within shared memory.
   * If a later one does, consider increasing the size returned by
   * get_queue_mem()
   */
  gasneti_sysvnet_allocator_t *a = gasneti_malloc(sizeof(gasneti_sysvnet_allocator_t));

  /* make sure we've arranged for block == page */
  gasneti_assert(sizeof(gasneti_sysvnet_allocator_block_t) == 17*GASNETI_SYSVNET_PAGESIZE);
  gasneti_assert_align(region, GASNETI_SYSVNET_PAGESIZE);

  a->queue = a->next = tmp = region;
  a->justpastlast = tmp + count;
  gasneti_mutex_init(&a->next_lock);
  for (i = 0; i < count; i++, tmp++) {
    gasneti_atomic_set(&tmp->alignmentFun.in_use, 0, 0);
  }
  return a;
}


static void * gasneti_sysvnet_alloc(gasneti_sysvnet_allocator_t *a, size_t nbytes)
{
  void *retval = NULL;

  gasneti_assert(nbytes <= sizeof(gasneti_sysvnet_payload_t));

  gasneti_mutex_lock(&a->next_lock);
  /* NOTE: I assume messages are generally consumed in serial order, so just
   * check the 'next' payload, rather than scan the whole array.  I believe
   * this is at least correct, but given that the payloads can go to different
   * receivers (who may take different times to get around to consuming them),
   * perhaps we ought to do a full scan?
   */
  if (!gasneti_atomic_read(&a->next->alignmentFun.in_use, 0)) {
    gasneti_atomic_set(&a->next->alignmentFun.in_use, 1, 0);
    retval = &a->next->payload_t;
    if (++a->next == a->justpastlast)
      a->next = a->queue;
  }
  gasneti_mutex_unlock(&a->next_lock);
  return retval;
}

static void gasneti_sysvnet_free(gasneti_sysvnet_allocator_t *a, void *p)
{
  /* We don't need the allocator ptr, but other implementations might  */

  /* Address we handed out was the addr of the 'payload_t' field */
  gasneti_sysvnet_allocator_block_t *block = 
      sysvnet_get_struct_addr_from_field_addr(gasneti_sysvnet_allocator_block_t,
                                              payload_t, p);
  gasneti_assert(p == &block->payload_t);
  /* assert block is page-aligned */
  gasneti_assert( (((uintptr_t)block) % GASNETI_SYSVNET_PAGESIZE) == 0);

  gasneti_atomic_set(&block->alignmentFun.in_use, 0, 0);
}

/******************************************************************************
 * AMSYSV:  Active Message API over Sysvnet
 ******************************************************************************/

typedef uint32_t gasneti_AMSYSV_category_t;
typedef uint32_t gasneti_AMSYSV_handler_t;

/* TODO: tweak data sizes?  */
typedef struct {
  gasneti_AMSYSV_category_t category;      /* AM msg type: small, med, large */
  gasneti_AMSYSV_handler_t handler_id;
  uint32_t numargs;
  gasnet_handlerarg_t args[GASNETC_MAX_ARGS_SYSV];
} gasneti_AMSYSV_msg_t;
typedef gasneti_AMSYSV_msg_t gasneti_AMSYSV_smallmsg_t;

typedef struct {
  gasneti_AMSYSV_msg_t msg;
  uint32_t numbytes;
  uint8_t  mediumdata[(size_t)GASNETC_MAX_MEDIUM_SYSV];
} gasneti_AMSYSV_medmsg_t;

typedef struct {
  gasneti_AMSYSV_msg_t msg;
  uint32_t numbytes;
  void *   longdata;
} gasneti_AMSYSV_longmsg_t;

#define GASNETI_AMSYSV_MSG_CATEGORY(msg)      (((gasneti_AMSYSV_msg_t*)msg)->category)
#define GASNETI_AMSYSV_MSG_HANDLERID(msg)     (((gasneti_AMSYSV_msg_t*)msg)->handler_id)
#define GASNETI_AMSYSV_MSG_NUMARGS(msg)       (((gasneti_AMSYSV_msg_t*)msg)->numargs)
#define GASNETI_AMSYSV_MSG_ARGS(msg)          (((gasneti_AMSYSV_msg_t*)msg)->args)
#define GASNETI_AMSYSV_MSG_MED_NUMBYTES(msg)  (((gasneti_AMSYSV_medmsg_t*)msg)->numbytes)
#define GASNETI_AMSYSV_MSG_MED_DATA(msg)      (((gasneti_AMSYSV_medmsg_t*)msg)->mediumdata)
#define GASNETI_AMSYSV_MSG_LONG_NUMBYTES(msg) (((gasneti_AMSYSV_longmsg_t*)msg)->numbytes)
#define GASNETI_AMSYSV_MSG_LONG_DATA(msg)     (((gasneti_AMSYSV_longmsg_t*)msg)->longdata)

#define GASNETI_AMSYSV_MAX_RECVMSGS_PER_POLL 10

/* ------------------------------------------------------------------------------------ */
GASNETI_INLINE(gasneti_AMSYSV_service_incoming_msg)
int gasneti_AMSYSV_service_incoming_msg(gasneti_sysvnet_t *vnet, int isReq)
{
  void *msg;
  size_t msgsz;
  gasnet_node_t from;
  gasneti_AMSYSV_category_t category;
  gasneti_AMSYSV_handler_t handler_id;
  void (*handler_fn)();
  int numargs;
  gasnet_handlerarg_t *args;
  gasnet_token_t token;

  if (gasneti_sysvnet_recv(vnet, &msg, &msgsz, &from))
    return -1;

  token = gasnetc_token_create(from, isReq);
  category = GASNETI_AMSYSV_MSG_CATEGORY(msg);
  gasneti_assert((category == gasnetc_Short) || 
                 (category == gasnetc_Medium) || 
                 (category == gasnetc_Long));
  handler_id = GASNETI_AMSYSV_MSG_HANDLERID(msg);
  handler_fn = gasnetc_get_handler(handler_id);
  numargs = GASNETI_AMSYSV_MSG_NUMARGS(msg);
  args = GASNETI_AMSYSV_MSG_ARGS(msg);

  switch (category) {
    case gasnetc_Short:
      { 
        GASNETI_RUN_HANDLER_SHORT(isReq,handler_id,handler_fn,token,args,numargs);
      }
      break;
    case gasnetc_Medium:
      {
        void * data = GASNETI_AMSYSV_MSG_MED_DATA(msg);
        size_t nbytes = GASNETI_AMSYSV_MSG_MED_NUMBYTES(msg);
        GASNETI_RUN_HANDLER_MEDIUM(
          isReq,handler_id,handler_fn,token,args,numargs,data,nbytes);
      }
      break;
    case gasnetc_Long:
      { 
        void * data = GASNETI_AMSYSV_MSG_LONG_DATA(msg);
        size_t nbytes = GASNETI_AMSYSV_MSG_LONG_NUMBYTES(msg);
        GASNETI_RUN_HANDLER_LONG(
            isReq,handler_id,handler_fn,token,args,numargs,data,nbytes);
      }
      break;
  }
  gasnetc_token_destroy(token);
  gasneti_sysvnet_recv_release(vnet, msg);
  return 0;
}

/* ------------------------------------------------------------------------------------ */
int gasneti_AMSYSVPoll(int repliesOnly)
{
  int i = 0;

  GASNETI_CHECKATTACH();

  for (; i < GASNETI_AMSYSV_MAX_RECVMSGS_PER_POLL; i++) 
    if (gasneti_AMSYSV_service_incoming_msg(gasneti_reply_sysvnet, 0))
      break;
  if (!repliesOnly)
    for (; i < GASNETI_AMSYSV_MAX_RECVMSGS_PER_POLL; i++) 
      if (gasneti_AMSYSV_service_incoming_msg(gasneti_request_sysvnet, 1))
        break;
  return GASNET_OK;
}

/* ------------------------------------------------------------------------------------ */
/*
 * Active Message Request Functions
 * ================================
 */

int gasnetc_AMSYSV_ReqRepGeneric(int category, int isReq, int dest,
                                 gasnet_handler_t handler, void *source_addr, int nbytes, 
                                 void *dest_addr, int numargs, va_list argptr) 
{
  gasneti_sysvnet_t *vnet = (isReq ? gasneti_request_sysvnet : gasneti_reply_sysvnet);
  int msgsz, i;
  void *msg;
  gasnet_handlerarg_t *pargs;
  int loopback = (dest == gasneti_mynode);

  gasneti_assert(vnet != NULL);

  //printf("%d> reqrep category=%d\n",gasneti_mysysvnode,category);
  /* calculate size of sysV buffer needed */
  switch (category) {
    case gasnetc_Short:
      msgsz = sizeof(gasneti_AMSYSV_smallmsg_t);
      break;
    case gasnetc_Medium:
      msgsz = sizeof(gasneti_AMSYSV_medmsg_t);
      break;
    case gasnetc_Long:
      msgsz = sizeof(gasneti_AMSYSV_longmsg_t);
      break;
    default:
      gasneti_fatalerror("internal error: unknown msg category");
  }
  gasneti_assert(msgsz <= GASNETI_SYSVNET_MAX_PAYLOAD); 

  /* Get buffer, poll if busy */
  if (loopback) {
    /* TODO: instead of doing a malloc each time, keep a per-thread pair of
     * medmsg-sized request/reply buffers, and use them.  See smp-conduit's
     * gasnetc_ReqRepGeneric's handling of mediummsgs */
    msg = gasneti_malloc(msgsz);
  } else {
    while (!(msg = gasneti_sysvnet_get_send_buffer(vnet, msgsz, dest))) {
      /* If reply, only poll reply network: avoids deadlock  */
      if (isReq) gasnetc_AMPoll(); /* No progress functions */
      else gasneti_AMSYSVPoll(1);
    }
  }

  /* Fill in message */
  GASNETI_AMSYSV_MSG_CATEGORY(msg) = category;
  GASNETI_AMSYSV_MSG_HANDLERID(msg) = handler;
  GASNETI_AMSYSV_MSG_NUMARGS(msg) = numargs;
  for(i = 0; i < numargs; i++) 
    GASNETI_AMSYSV_MSG_ARGS(msg)[i] = (gasnet_handlerarg_t)va_arg(argptr, int);

  switch (category) {
    case gasnetc_Short:
      break;
    case gasnetc_Medium:
      GASNETI_AMSYSV_MSG_MED_NUMBYTES(msg) = nbytes;
      memcpy(GASNETI_AMSYSV_MSG_MED_DATA(msg), source_addr, nbytes);
      break;
    case gasnetc_Long: {
      void *local_dest_addr = (void*)((uintptr_t)dest_addr
                                      - (uintptr_t)gasneti_seginfo[dest].addr
                                      + (uintptr_t)gasneti_seginfo[dest].remote_addr);

      GASNETI_AMSYSV_MSG_LONG_DATA(msg) = dest_addr; 
      GASNETI_AMSYSV_MSG_LONG_NUMBYTES(msg) = nbytes;
      /* deliver_msg call, below, contains write flush, so don't need here */
      memcpy(local_dest_addr, source_addr, nbytes);
      break;
    }
  }

  /* Deliver message */
  if (loopback) {
    gasneti_handler_fn_t handler_fn = gasnetc_get_handler(handler); 
    gasnet_token_t token = gasnetc_token_create(gasneti_mynode, isReq);
    gasnet_handlerarg_t *args = GASNETI_AMSYSV_MSG_ARGS(msg);
    switch (category) {
      case gasnetc_Short:
        GASNETI_RUN_HANDLER_SHORT(isReq,handler,handler_fn,token,args,numargs);

        break;
      case gasnetc_Medium:
        GASNETI_RUN_HANDLER_MEDIUM(isReq, handler, handler_fn, token, args, numargs,
                                   GASNETI_AMSYSV_MSG_MED_DATA(msg), nbytes);
        break;
      case gasnetc_Long:
        gasneti_local_wmb(); /* sync memcpy, above */
        GASNETI_RUN_HANDLER_LONG(isReq, handler, handler_fn, token, args, numargs,
                                 dest_addr, nbytes);
        break;
    }
    gasneti_free(msg);
    gasnetc_token_destroy(token);
  } else {
    
    while (gasneti_sysvnet_deliver_send_buffer(vnet, msg, msgsz, dest)) {
      /* If reply, only poll reply network: avoids deadlock  */
      if (isReq) gasnetc_AMPoll(); /* No progress functions */
      else gasneti_AMSYSVPoll(1);
    }
  }
  return GASNET_OK;
}

#endif /* GASNET_SYSV */
