#   $Source: /Users/kamil/work/gasnet-cvs2/gasnet/other/amudp/Makefile.generic,v $
#     $Date: 2006/06/06 22:35:24 $
# $Revision: 1.1.2.1 $
# Description: Linux Makefile fragment
# Copyright 2000, Dan Bonachea <bonachea@cs.berkeley.edu>

# additional defines required to build on this platform
platform_defines = 

# additional linker flags required to build on this platform
platform_ldflags = 

# additional libraries and/or library directories
platform_libraries =
