#  $Archive:: /Ti/AMMPI/Makefile.common                                  $
#     $Date: 2004/04/20 00:24:27 $
# $Revision: 1.5.4.2 $
# Description: Platform-independent variable init, overridden by pre-baked makefiles
# Copyright 2000, Dan Bonachea <bonachea@cs.berkeley.edu>

# variables added here should also go in Makefile.titanium.in, and vice-versa

srcdir = .
altincdir = $(srcdir)
testdir = $(srcdir)

# compiler
CC = mpicc
ccdebugflags = -O0 -g3 -ansi -Wall -Wno-unused-variable -Wno-unused-function
ccoptflags = -O3

# system utilities
ranlib = ranlib
ar = ar

# To be set by pre-baked makefiles:
endianness = 
platform_defines = 
platform_ldflags =
platform_libraries = 
