// This is *not* a normative document.
// It is a place for collection of agreed-upon APIs and for initial
// drafting of what may become the normative text.

// A "handle" is an opaque scalar type
// - Sync operation: test/wait w/ one/all/some flavors
//   + Success consumes the handle
struct gasneti_handle_t;
typedef struct gasneti_handle_t *gasnetex_handle_t;

// Pre-defined output values of type gasnetex_handle_t
// - GASNETEX_INVALID_HANDLE
//   + result for already-completed operation
// - GASNETEX_NO_OP_HANDLE
//   + Erroneous to pass this value to test/wait operations
#define GASNETEX_INVALID_HANDLE      ((gasnetex_handle_t)(uintptr_t)0)
#define GASNETEX_NO_OP_HANDLE        ((gasnetex_handle_t)(uintptr_t)1)

// Pre-defined input values of type gasnetex_handle_t*
// - GASNETEX_EVENT_NOW
//   + Pass to require completion within the initiation call
// - GASNETEX_EVENT_DEFER
//   + Pass to allow completion as late as completion of the parent
// - GASNETEX_EVENT_GROUP
//   + Pass to NBI initiation calls to allow client to use NBI-based
//     calls to detect event completion (or to use an explicit handle
//     returned/generated by gasnetex_end_nbi_accessregion()).
#define GASNETEX_EVENT_NOW    ((gasnetex_handle_t*)(uintptr_t)1)
#define GASNETEX_EVENT_DEFER  ((gasnetex_handle_t*)(uintptr_t)2)
#define GASNETEX_EVENT_GROUP  ((gasnetex_handle_t*)(uintptr_t)3)

// A "team member" is an opaque scalar type
struct gasneti_team_member_s;
typedef struct gasneti_team_member_s *gasnetex_team_member_t;

// A "rank" is a position within a team
typedef uint32_t gasnetex_rank_t;

// Assume no more than 32 flags will be needed for any one family of calls
// However, flags to p2p initiation and segment creation (as examples) could overlap
typedef uint32_t gasnetex_flags_t;

// SOME flags values - certainly not complete.
// NOTE: Shifts of '999' are being used until the list is more fleshed out,
// and with the hope that a compiler warning about "shift larger than width"
// will ensure we fix them all eventually.
enum {
  //
  // Flags for point-to-point communication initiation
  //
      //
      // {SRC,DST}_OFFSET
      //
      // These flag bits indicate that the corresponding address argument
      // is an *offset* relative to the segment base.
      GASNETEX_FLAG_SRC_OFFSET = (1 << 999),
      GASNETEX_FLAG_DST_OFFSET = (1 << 999),
      //
      // IMMEDIATE
      //
      // This flag indicates that GASNet-EX *may* return without initiating
      // any communication if the conduit could determine that it would
      // need to block temporarily to obtain the necessary resources.  In
      // this case calls with return type 'gasnetex_handle_t' return
      // GASNETEX_NO_OP_HANDLE while those with return type 'int' will
      // return non-zero.
      //
      GASNETEX_FLAG_IMMEDIATE = (1 << 999),
      //
      // LC_COPY_{YES,NO}
      //
      // This mutually-exclusive pair of flags *may* override GASNet-EX's
      // choice of whether or not to make a copy of a payload (of a
      // non-blocking Put or AM) for the purpose of accelerating local
      // completion.  In the absence of these flags the conduit-specific
      // logic will apply.
      //
      // NOTE: these need more thought w.r.t. the implementation and
      // specification
      GASNETEX_FLAG_LC_COPY_YES = (1 << 999),
      GASNETEX_FLAG_LC_COPY_NO  = (1 << 999),
      //
      // {SRC,DST}_IN_SEGMENT
      //
      // These flag bits assert that for the coresponding source or
      // destination address the range of bytes [address, address+nbytes)
      // is contained within the union of current GASNet-EX segments.  In
      // the case of offset-based addressing the assertion is redundant,
      // but is still legal.
      GASNETEX_FLAG_SRC_IN_SEGMENT = (1 << 999),
      GASNETEX_FLAG_DST_IN_SEGMENT = (1 << 999),
};

// A "token" is an opaque scalar type
struct gasneti_token_s;
typedef struct gasneti_token_s *gasnetex_token_t;

// Handler index and argument types are fixed-width integers
typedef uint8_t gasnetex_handler_t;
typedef int32_t gasnetex_handlerarg_t;

// Widest scalar and width
typedef uintptr_t gasnetex_register_value_t;
#define GASNETEX_REGISTER_VALUE_T SIZEOF_VOID_P

// The following are the *internal* prototypes for AM Request and Reply
// The public API "instantiates" the "M" and the argument list.
// 
// NOTE 1: Return value
// 
//   An AM Request or Reply call is a "no op" IF AND ONLY IF the value
//   GASNETEX_FLAG_IMMEDIATE is included in the 'flags' argument AND the
//   conduit could determine that it would need to block temporarily to
//   obtain the necessary resources.  This case is distinguished by a
//   non-zero return.  In all other cases the return value is zero.  
//
//   In the "no op" case no communication has been performed and the
//   contents of the location named by the 'lc_opt' argument (if any) is
//   undefined.
//
// NOTE 2: The 'lc_opt' argument for local completion
//
//   The AM interfaces never detect or report remote completion, but do
//   have selectable behavior with respect to local completion (which
//   means that the payload buffer may safely by written, free()ed, etc).
//
//   Short AMs have no payload and therefore have no 'lc_opt' argument.
//
//   The Medium and Long Requests accept the pre-defined constant values
//   GASNETEX_EVENT_NOW and GASNETEX_EVENT_GROUP, and pointers to variables of
//   type 'gasnetex_handle_t'.  The NOW constant requires that the
//   Request call not return until after local completion.  The GROUP
//   constant allows the Request call to return without delaying for local
//   completion and adds the AM operation to the set of operations for
//   which the "LCnbi" calls [NAMES TBD] will check local completion.  Use
//   of a pointer to a variable of type 'gasnetex_handle_t' allows the
//   call to return without delay, and requres the client to use the "LCnb"
//   calls [NAMES TBD] to check local completion.
//
//   The 'lc_opt' argument to Medium and Long Reply calls behave as for the
//   Requests with the exception that GASNETEX_EVENT_GROUP is *not* permitted.
//   It is also important to note that it is not legal to "test", or
//   "wait" on a 'gasnetex_handle_t' in AM handler context.
//   [TBD: we *could* allow handlers to make bounded calls to "test", which
//   does not Poll, if we wanted to.]

// Long
int gasnetex_AMRequestLongM(
           gasnetex_team_member_t team,   // Names a local context ("return address")
           gasnetex_rank_t rank,          // Together with 'team', names a remote context
           gasnetex_handler_t handler,    // Index into handler table of remote context
           const void *source_addr,       // Payload address (or OFFSET)
           size_t nbytes,                 // Payload length
           void *dest_addr,               // Payload destination address (or OFFSET)
           gasnetex_handle_t *lc_opt,     // Local completion control (see above)
           gasnetex_flags_t flags,        // Flags to control this operation
           int numargs, ...);             // Argument list (0..AMMaxArgs) as varargs
int gasnetex_AMReplyLongM(
           gasnetex_token_t token,        // Names local and remote contexts
           gasnetex_handler_t handler,
           const void *source_addr,
           size_t nbytes,
           void *dest_addr,
           gasnetex_handle_t *lc_opt,
           gasnetex_flags_t flags,
           int numargs, ...);
// Medium
int gasnetex_AMRequestMediumM(
           gasnetex_team_member_t team,
           gasnetex_rank_t rank,
           gasnetex_handler_t handler,
           const void *source_addr,
           size_t nbytes,
           gasnetex_handle_t *lc_opt,
           gasnetex_flags_t flags,
           int numargs, ...);
int gasnetex_AMReplyMediumM(
           gasnetex_token_t token,
           gasnetex_handler_t handler,
           const void *source_addr,
           size_t nbytes,
           gasnetex_handle_t *lc_opt,
           gasnetex_flags_t flags,
           int numargs, ...);
// Short
int gasnetex_AMRequestShortM(
           gasnetex_team_member_t team,
           gasnetex_rank_t rank,
           gasnetex_handler_t handler, 
           gasnetex_flags_t flags,
           int numargs, ...);
int gasnetex_AMReplyShortM(
           gasnetex_token_t token,
           gasnetex_handler_t handler,
           gasnetex_flags_t flags,
           int numargs, ...);

// Extended API
//
// NOTE 1: Return value
//
//   An Extended API initiation call is a "no op" IF AND ONLY IF the value
//   GASNETEX_FLAG_IMMEDIATE is included in the 'flags' argument AND the
//   conduit could determine that it would need to block temporarily to
//   obtain the necessary resources.  The blocking and nbi calls return a
//   non-zero value *only* in the "no op" case, while the nb calls return
//   GASNETEX_NO_OP_HANDLE.
//
//   In the "no op" case no communication has been performed and the
//   contents of the location named by the 'lc_opt' argument (if any) is
//   undefined.
//
// NOTE 2a: The 'lc_opt' argument for local completion (NBI case)
//
//   Implicit-handle non-blocking Puts have an 'lc_opt' argument which
//   controls the behavior with respect to local completion.  The value can
//   be the pre-defined constants GASNETEX_EVENT_NOW, GASNETEX_EVENT_DEFER, or
//   GASNETEX_EVENT_GROUP.  The NOW constant requires that the call not
//   return until the operation is locally complete.  The DEFER constant
//   permits the call to return without delaying for local completion,
//   which may occur as late as in the call which syncs (retires) the
//   operation (could be an explicit-handle call if using an nbi
//   access region).  The GROUP constant allows the Request call to return
//   without delaying for local completion and adds the Put operation to
//   the set of operations for which the "LCnbi" calls [NAMES TBD] will
//   check local completion.
//
// NOTE 2b: The 'lc_opt' argument for local completion (NB case)
//
//   Explicit-handle non-blocking Puts have an 'lc_opt' argument which
//   controls the behavior with respect to local completion.  The value can
//   be the pre-defined constants GASNETEX_EVENT_NOW or GASNETEX_EVENT_DEFER, or
//   a pointer to a variable of type 'gasnetex_handle_t'.  The NOW
//   constant requires that the call not return until the operation is
//   locally complete.  The DEFER constant permits the call to return
//   without delaying for local completion, which may occur as late as in
//   the call which syncs (retires) the returned handle.  Use of a pointer
//   to a variable of type 'gasnetex_handle_t' allows the call to return
//   without delay, and requires that the client use the "LCnb" calls
//   [NAMES TBD] to check for local completion.

// Put
int gasnetex_put(
           gasnetex_team_member_t team,   // Names a local context ("return address")
           gasnetex_rank_t rank,          // Together with 'team', names a remote context
           void *dest,                    // Remote (destination) address (or OFFSET)
           const void *src,               // Local (source) address (or OFFSET)
           size_t nbytes,                 // Length of xfer
           gasnetex_flags_t flags);       // Flags to control this operation
int gasnetex_put_nbi(
           gasnetex_team_member_t team,
           gasnetex_rank_t rank,
           void *dest,
           const void *src,
           size_t nbytes,
           gasnetex_handle_t *lc_opt,     // Local completion control (see above)
           gasnetex_flags_t flags);
gasnetex_handle_t gasnetex_put_nb(
           gasnetex_team_member_t team,
           gasnetex_rank_t rank,
           void *dest,
           const void *src,
           size_t nbytes,
           gasnetex_handle_t *lc_opt,
           gasnetex_flags_t flags);

// Get
int gasnetex_get( // Returns non-zero *only* in "no op" case (IMMEDIATE flag)
           gasnetex_team_member_t team,   // Names a local context ("return address")
           void *dest,                    // Local (destination) address (or OFFSET)
           gasnetex_rank_t rank,          // Together with 'team', names a remote context
           void *src,                     // Remote (source) address (or OFFSET)
           size_t nbytes,                 // Length of xfer
           gasnetex_flags_t flags);       // Flags to control this operation
int gasnetex_get_nbi( // Returns non-zero *only* in "no op" case (IMMEDIATE flag)
           gasnetex_team_member_t team,
           void *dest,
           gasnetex_rank_t rank,
           void *src,
           size_t nbytes,
           gasnetex_flags_t flags);
gasnetex_handle_t gasnetex_get_nb(
           gasnetex_team_member_t team,
           void *dest,
           gasnetex_rank_t rank,
           void *src,
           size_t nbytes,
           gasnetex_flags_t flags);

// Value-based
gasnetex_register_value_t gasnetex_get_val(
           gasnetex_team_member_t team,
           gasnetex_rank_t rank,
           void *src,
           size_t nbytes,
           gasnetex_flags_t flags);
int gasnetex_put_val(
           gasnetex_team_member_t team,
           gasnetex_rank_t rank,
           void *dest,
           gasnetex_register_value_t value,
           size_t nbytes,
           gasnetex_flags_t flags);
int gasnetex_put_nbi_val(
           gasnetex_team_member_t team,
           gasnetex_rank_t rank,
           void *dest,
           gasnetex_register_value_t value,
           size_t nbytes,
           gasnetex_flags_t flags);
gasnetex_handle_t gasnetex_put_nb_val(
           gasnetex_team_member_t team,
           gasnetex_rank_t rank,
           void *dest,
           gasnetex_register_value_t value,
           size_t nbytes,
           gasnetex_flags_t flags);

// NBI Access regions:
// Note: no defined values for 'flags' for either call yet.

void gasnetex_begin_nbi_accessregion(gasnetex_flags_t flags);
gasnetex_handle_t gasnetex_end_nbi_accessregion(gasnetex_flags_t flags);


// Handle test/wait operations
// The operation is indicated by the suffix
//  + _test: no Poll call is made, returns zero on success, and non-zero otherwise.
//  + _wait: Polls until success, no return

// Completion of a single NB handle
// Success is defined as when the passed handle is complete.
int  gasnetex_test (gasnetex_handle_t handle);
void gasnetex_wait (gasnetex_handle_t handle);

// Completion of an NB handle array - "some"
// Success is defined as one or more handles have been completed, OR
// the input array contains only GASNETEX_INVALID_HANDLE.
// Completed handles, if any, are overwritten with GASNETEX_INVALID_HANDLE.
int  gasnetex_test_some (gasnetex_handle_t *phandle, size_t numhandles);
void gasnetex_wait_some (gasnetex_handle_t *phandle, size_t numhandles);

// Completion of an NB handle array - "all"
// Success is defined as all passed handles have been completed, OR
// the input array contains only GASNETEX_INVALID_HANDLE.
// Completed handles, if any, are overwritten with GASNETEX_INVALID_HANDLE.
int  gasnetex_test_all (gasnetex_handle_t *phandle, size_t numhandles);
void gasnetex_wait_all (gasnetex_handle_t *phandle, size_t numhandles);

// Sync of NBI gets
int  gasnetex_test_syncnbi_gets(void);
void gasnetex_wait_syncnbi_gets(void);

// Sync of NBI puts
int  gasnetex_test_syncnbi_puts(void);
void gasnetex_wait_syncnbi_puts(void);

// Sync of all NBI operations
int  gasnetex_test_syncnbi_all (void);
void gasnetex_wait_syncnbi_all (void);

// Sync of other events (such as local completion from NBI Puts)
enum gasnete_event {
  GASNETEX_EVENT_ALL,
  GASNETEX_EVENT_GETS,
  GASNETEX_EVENT_PUTS,
  GASNETEX_EVENT_LC,
};
int  gasnetex_test_syncnbi(enum gasnete_event);
void gasnetex_wait_syncnbi(enum gasnete_event);


// Pre-defined constant used to apply a query to all ranks in the team
#define GASNETEX_ALL_RANKS (~(gasnetex_rank_t)0)

// Max payload queries for specific peer, nargs, lc_opt and flags
// rank == GASNETEX_ALL_RANKS yields min-of-maxes
size_t gasnetex_max_AMRequestLong(
           gasnetex_team_member_t team,
           gasnetex_rank_t rank,
           gasnetex_handle_t *lc_opt,
           gasnetex_flags_t flags,
           int numargs);
size_t gasnetex_max_AMReplyLong(
           gasnetex_team_member_t team,
           gasnetex_rank_t rank,
           gasnetex_handle_t *lc_opt,
           gasnetex_flags_t flags,
           int numargs);
size_t gasnetex_max_AMRequestMedium(
           gasnetex_team_member_t team,
           gasnetex_rank_t rank,
           gasnetex_handle_t *lc_opt,
           gasnetex_flags_t flags,
           int numargs);
size_t gasnetex_max_AMReplyMedium(
           gasnetex_team_member_t team,
           gasnetex_rank_t rank,
           gasnetex_handle_t *lc_opt,
           gasnetex_flags_t flags,
           int numargs);

// Least-upper-bound payload queries (unknown peer, nargs, lc_opt and flags)
size_t gasnetex_lub_AMRequestLong(void);
size_t gasnetex_lub_AMReplyLong(void);
size_t gasnetex_lub_AMRequestMedium(void);
size_t gasnetex_lub_AMReplyMedium(void);

// vim: syntax=c
