#=============================================================================
# GasNetAtomics.cmake - Atomic operations detection
#=============================================================================
# Values from gasnet_atomic_fwd.h:
#   GASNETI_ATOMIC_IMPL_GENERIC=0, NATIVE=1, OS=2, SYNC=3, HYBRID=4, SPECIAL=5
include(CheckCSourceCompiles)

# Force options override
if(GASNET_FORCE_GENERIC_ATOMICOPS)
  set(GASNETI_ATOMIC_IMPL_CONFIGURE 0)
  set(GASNETI_ATOMIC32_IMPL_CONFIGURE 0)
  set(GASNETI_ATOMIC64_IMPL_CONFIGURE 0)
  return()
endif()
if(GASNET_FORCE_OS_ATOMICOPS)
  set(GASNETI_ATOMIC_IMPL_CONFIGURE 2)
  set(GASNETI_ATOMIC32_IMPL_CONFIGURE 2)
  set(GASNETI_ATOMIC64_IMPL_CONFIGURE 2)
  return()
endif()
if(GASNET_FORCE_COMPILER_ATOMICOPS)
  set(GASNETI_ATOMIC_IMPL_CONFIGURE 3)
  set(GASNETI_ATOMIC32_IMPL_CONFIGURE 3)
  set(GASNETI_ATOMIC64_IMPL_CONFIGURE 3)
  return()
endif()

# Choose best: NATIVE for known architectures with GCC/Clang, else SYNC, else GENERIC
if(GASNETI_HAVE_CC_GCC_ASM AND (GASNET_PLATFORM_ARCH STREQUAL "X86_64" OR
   GASNET_PLATFORM_ARCH STREQUAL "X86" OR GASNET_PLATFORM_ARCH STREQUAL "AARCH64" OR
   GASNET_PLATFORM_ARCH STREQUAL "PPC64" OR GASNET_PLATFORM_ARCH STREQUAL "ARM"))
  set(GASNETI_ATOMIC_IMPL_CONFIGURE 1)  # NATIVE
  set(GASNETI_ATOMIC32_IMPL_CONFIGURE 1)
  set(GASNETI_ATOMIC64_IMPL_CONFIGURE 1)
elseif(GASNETI_HAVE_CC_SYNC_ATOMICS_32)
  set(GASNETI_ATOMIC_IMPL_CONFIGURE 3)  # SYNC
  set(GASNETI_ATOMIC32_IMPL_CONFIGURE 3)
  set(GASNETI_ATOMIC64_IMPL_CONFIGURE 3)
else()
  set(GASNETI_ATOMIC_IMPL_CONFIGURE 0)  # GENERIC
  set(GASNETI_ATOMIC32_IMPL_CONFIGURE 0)
  set(GASNETI_ATOMIC64_IMPL_CONFIGURE 0)
endif()
